---
# This should be overriden
configuration_name: name
configuration_stage: stage
configuration_variant: variant

kubespray_patch_prefix: patched
configurations: []
external_inventory_configurations: []
reset_configurations: []

kubespray_git_repository: https://github.com/kubernetes-sigs/kubespray

#kubespray_git_version: 92e8ac9de236e9d3a3c29d2229722798f0e5fa2c
kubespray_git_version: c7c3d2ba95255c64cbbc40142f15a3f9d0cdf314
kubespray_git_folder: "{{ playbook_dir }}/target"

kube_oidc_enabled: true
kube_lodabalancer_apiserver_enabled: false
crio_enabled: true
cilium_version: "1.17.4"
kube_version: "1.32.5"
ipv6_stack: false

local_path_provisioner_claim_root: /opt/local-path-provisioner/
local_volume_provisioner_enabled: false

apiserver_loadbalancer_domain_name: ""
# This flag needs to be set in 1.14.*  to true if you want cilium
# the original approach doesn't work because it fits only for cilum <= 1.13
kubespray_kube_proxy_remove: false

loadbalancer_apiserver_address: ""
loadbalancer_apiserver_port: ""

external_loadbalancer_ip: ""
external_loadbalancer_port: 0
kube_apiserver_feature_gates: []
kube_api_runtime_config: []

# enable ipv6
enable_dual_stack_networks: false
