---
kubespray_patch_prefix: patched
configurations: []
external_inventory_configurations: []
reset_configurations: []

kubespray_git_repository: https://github.com/kubernetes-sigs/kubespray
# kubespray_git_version: b321ca3e640335fa1d0cdb9968e53cf92fc1cb1c
kubespray_git_version: aea150e5dc244e933c6d5e2aee35ffb7ffe614a9
kubespray_git_folder: "{{ playbook_dir }}/target"

kube_oidc_enabled: true
kube_lodabalancer_apiserver_enabled: false
crio_enabled: true
cilium_version: "v1.14.5"
kube_version: "v1.28.5"

local_path_provisioner_claim_root: /opt/local-path-provisioner/
local_volume_provisioner_enabled: false

apiserver_loadbalancer_domain_name: ""
# This flag needs to be set in 1.14.*  to true if you want cilium
# the original approach doesn't work because it fits only for cilum <= 1.13
kubespray_kube_proxy_remove: false

loadbalancer_apiserver_address: ""
loadbalancer_apiserver_port: ""

external_loadbalancer_ip: ""
external_loadbalancer_port: 0
kube_apiserver_feature_gates: []
kube_api_runtime_config: []
