---
- name: Cilium | Prepare fallback DNS configuration
  block:
    - name: Create directory for resolved configuration
      ansible.builtin.file:
        dest: "/etc/systemd/resolved.conf.d"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create fallback DNS configuration file
      ansible.builtin.copy:
        dest: "/etc/systemd/resolved.conf.d/dns_servers.conf"
        content: |-
          [Resolve]
          DNS={{ upstream_dns_servers[0] }}
          Domains=~.
        mode: '0644'
      register: copy_result

    - name: Restart systemd-resolved service
      ansible.builtin.systemd:
        state: restarted
        name: systemd-resolved
      when: copy_result.changed

- name: Cilium | Ensure BPFFS is mounted
  # ansible.builtin.mount:
  ansible.posix.mount:
    fstype: bpf
    path: /sys/fs/bpf
    src: bpffs
    state: mounted

- name: Cilium | Set up certificate directories and files
  when: cilium_identity_allocation_mode == "kvstore"
  block:
    - name: Create Cilium certificates directory
      ansible.builtin.file:
        dest: "{{ cilium_cert_dir }}"
        state: directory
        mode: '0750'
        owner: root
        group: root

    - name: Copy etcd certificates for Cilium
      ansible.builtin.copy:
        remote_src: true
        src: "{{ etcd_cert_dir }}/{{ item.s }}"
        dest: "{{ cilium_cert_dir }}/{{ item.d }}"
        mode: '0644'
      loop:
        - { s: "ca.pem", d: "ca_cert.crt" }
        - { s: "node-{{ inventory_hostname }}.pem", d: "cert.crt" }
        - { s: "node-{{ inventory_hostname }}-key.pem", d: "key.pem" }

- name: Cilium | Enable portmap addon
  when: cilium_enable_portmap
  ansible.builtin.template:
    src: 000-cilium-portmap.conflist.j2
    dest: /etc/cni/net.d/000-cilium-portmap.conflist
    mode: '0644'

- name: Cilium | Forbid systemd-udevd to manage cilium network devices
  ansible.builtin.template:
    src: 20-cilium.link.j2
    dest: /etc/systemd/network/20-cilium.link
    mode: '0644'
  register: systemd_udevd_network_cilium

- name: Cilium | Restart systemd-udevd service
  when: systemd_udevd_network_cilium.changed
  ansible.builtin.systemd:
    state: restarted
    name: systemd-udevd
