---
- name: Add files to git
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - add
      - "{{ item }}"
  loop: "{{ git_file_list }}"
  tags:
    - skip_ansible_lint

- name: Commit changes
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - commit
      - -m
      - "{{ git_message }}"
  tags:
    - skip_ansible_lint
