---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ kubespray_git_folder }}/bin"
    state: directory
    mode: '0755'

- name: Set fact
  ansible.builtin.set_fact:
    git_file_list:
      - bin/kubespray.sh
      - bin/reset.sh
    git_message: |
      kubespray.sh which going to be symlinked
      usually not called directly but with a symlink

- name: Copy bin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kubespray_git_folder }}/{{ item }}"
    mode: '0755'
  loop: "{{ git_file_list }}"

- name: Commit files to git
  ansible.builtin.include_tasks: commit-files.yml

- name: Create a symbolic link
  ansible.builtin.file:
    src: "./bin/kubespray.sh"
    dest: "{{ kubespray_git_folder }}/{{ item }}"
    state: link
  loop: "{{ configurations }}"

- name: Create a symbolic link for configuration reset
  ansible.builtin.file:
    src: "./bin/reset.sh"
    dest: "{{ kubespray_git_folder }}/{{ item }}"
    state: link
  loop: "{{ reset_configurations }}"

- name: Create a symbolic link for configuration upgrade
  ansible.builtin.file:
    src: "./bin/kubespray.sh"
    dest: "{{ kubespray_git_folder }}/{{ item }}"
    state: link
  loop: "{{ upgrade_configurations }}"

- name: Create a symbolic link for external inventories
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ kubespray_git_folder }}/inventory/{{ item.dest }}"
    state: link
  loop: "{{ external_inventory_configurations }}"

- name: Set fact
  ansible.builtin.set_fact:
    git_file_list: "{{ configurations + upgrade_configurations + reset_configurations }}"
    git_message: |
      All symlinks specific to this setup

- name: Commit files to git
  ansible.builtin.include_tasks: commit-files.yml

- name: CRIO
  when: crio_enabled
  block:
    - name: Patch kubespray for nvidia-operator support
      ansible.builtin.replace:
        path: "{{ kubespray_git_folder }}/roles/container-engine/cri-o/templates/crio.conf.j2"
        regexp: "^[ \t]+\"/usr/share/containers/oci/hooks.d\",$"
        replace: "        \"/etc/containers/oci/hooks.d\", \"/usr/share/containers/oci/hooks.d\","
      tags:
        - skip_ansible_lint

    - name: Set fact
      ansible.builtin.set_fact:
        git_file_list:
          - roles/container-engine/cri-o/templates/crio.conf.j2
        git_message: |
          enable availability of /etc/containers/oci/hooks.d in crio.conf for the nvidia gpu-operator

    - name: Commit files to git
      ansible.builtin.include_tasks: commit-files.yml

    #  Patch /var/run/crio (<=1.24 crio bug)
    #  https: //github.com/ocf/puppet/commit/c436362078f997a86f1c494903f74bf78b2ccdf2
    - name: Patch patch path /var/run/crio to /run/crio
      ansible.builtin.replace:
        path: "{{ kubespray_git_folder }}/roles/kubespray-defaults/defaults/main.yaml"
        regexp: "/var/run/crio/"
        replace: "/run/crio/"

    - name: Set fact
      ansible.builtin.set_fact:
        git_file_list:
          - roles/kubespray-defaults/defaults/main.yaml
        git_message: |
          Patch /var/run/crio to /run/crio for crio <= 1.24 due the following bug
          https: //github.com/ocf/puppet/commit/c436362078f997a86f1c494903f74bf78b2ccdf2
          the CRI-O team found performance issues in the CRI stats provider, so there's
          a hack in kubelet which falls back to cadvisor when crio is being used.
          This is currently broken and causing a bunch of spam in our logs that looks
          like  "Unable to fetch pod log stats" -- leading to some nodes (like jaws,
          with a 64G disk) to become NotReady due to disk pressure.
          This commit works around the above issue by subverting the string check
          using the fact that `/run` is symlinked to `/var/run`.

    - name: Commit files to git
      ansible.builtin.include_tasks: commit-files.yml

# FIXME really needed for v1.26.* ?

- name: Patch kubelet.env to remove cadvisor failure reporting in logs
  ansible.builtin.lineinfile:
    dest: "{{ kubespray_git_folder }}/roles/kubernetes/node/templates/kubelet.env.v1beta1.j2"
    insertafter: "--runtime-cgroups={% raw %}{{ kubelet_runtime_cgroups }}{% endraw %} \\\\"
    line: "--kubelet-cgroups={% raw %}{{ kubelet_runtime_cgroups }}{% endraw %} \\"

- name: Set fact
  ansible.builtin.set_fact:
    git_file_list:
      - roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
    git_message: |
      avoid a lot of error messages because of cadvisor failure in kubelet

- name: Commit files to git
  ansible.builtin.include_tasks: commit-files.yml

#      - { role: kubernetes-apps/cluster_roles, tags: cluster-roles }
# +    - { role: kubernetes-apps/helm, tags: helm }

- name: Patch cluster.yml for early helm availability
  ansible.builtin.lineinfile:
    dest: "{{ kubespray_git_folder }}/playbooks/cluster.yml"
    insertafter: "    - { role: kubernetes-apps/cluster_roles, tags: cluster-roles }"
    line: "    - { role: kubernetes-apps/helm, tags: helm }"

- name: Set fact
  ansible.builtin.set_fact:
    git_file_list:
      - playbooks/cluster.yml
    git_message: |
      make helm binary available before we go to network_plugin install

- name: Commit files to git
  ansible.builtin.include_tasks: commit-files.yml

- name: Set Fact
  ansible.builtin.set_fact:
    cilium_template_version: 1.13.0
  when: cilium_version[1:] is version('1.13.1', '<')

- name: Set Fact
  ansible.builtin.set_fact:
    cilium_template_version: 1.13.1
  when: cilium_version[1:] is version('1.13.1', '>=')

- name: Copy cilium template
  ansible.builtin.copy:
    src: "cilium-values-{{ cilium_template_version }}.yml.j2"
    dest: "{{ kubespray_git_folder }}/roles/network_plugin/cilium/templates/cilium-values.yml.j2"
    mode: 0644

- name: Set Facts
  ansible.builtin.set_fact:
    file_list:
      - roles/network_plugin/cilium/tasks/apply.yml
      - roles/network_plugin/cilium/tasks/install.yml

- name: Copy Files
  ansible.builtin.copy:
    src: "{{ item | basename }}"
    dest: "{{ kubespray_git_folder }}/{{ item }}"
    mode: 0644
  loop: "{{ file_list }}"

- name: Set fact
  ansible.builtin.set_fact:
    git_file_list: "{{ file_list + ['roles/network_plugin/cilium/templates/cilium-values.yml.j2'] }}"
    git_message: |
      deploy cilium as helm chart

- name: Commit files to git
  ansible.builtin.include_tasks: commit-files.yml

#  diff --git a/roles/container-engine/cri-o/tasks/crio_repo.yml b/roles/container-engine/cri-o/tasks/crio_repo.yml
#  index f2b1b71a..08bcce17 100644
#  --- a/roles/container-engine/cri-o/tasks/crio_repo.yml
#  +++ b/roles/container-engine/cri-o/tasks/crio_repo.yml
#  @@ -149,7 +149,7 @@
#         section: "fedora-modular"
#
#   - name: Enable CRI-O ex module
#  -  command: "rpm-ostree ex module enable cri-o:{{ crio_version }}"
#  +  command: "echo rpm-ostree ex module enable cri-o:{{ crio_version }}"
#     become: true
#     when:
#       - is_ostree

- name: Set facts
  ansible.builtin.set_fact:
    patch_file: etcd-v4.patch
    git_message: |
      Enable for the etcd to not run in a virtual machine, but run in a lxc container
      as it is provided by proxmox. An Lxc Container has no swap file

- name: Apply patch for supporting etcd as container
  ansible.builtin.include_tasks: apply-patch.yml

#- name: Set facts
#  ansible.builtin.set_fact:
#    patch_file: fedora-38-ansible.patch
#    git_message: |
#      Support new ansible in fedora 38
#
#- name: Apply patch for support of the new ansible version in fedora
#  ansible.builtin.include_tasks: apply-patch.yml


#- name: Quirk somehow multus is called which is not intended
#  ansible.builtin.replace:
#    path: "{{ kubespray_git_folder }}/roles/kubernetes-apps/network_plugin/multus/tasks/main.yml"
#    regexp: '^([^#])(.*)'
#    replace: '# \1\2'
#
#- name: Set facts
#  ansible.builtin.set_fact:
#    git_file_list:
#      - roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
#    git_message: |
#      Workaround multus step, which happens to fail in my setup
#
#- name: Commit files to git
#  ansible.builtin.include_tasks: commit-files.yml

- name: Set facts
  ansible.builtin.set_fact:
    patch_file: kubeadm-setup-race-condition-v3.patch
    git_message: |
      Fix race condition in kubeadm-setup.yml

- name: Apply patch for race condition fix in kubeadm-setup
  ansible.builtin.include_tasks: apply-patch.yml

- name: Set facts
  ansible.builtin.set_fact:
    patch_file: roles-kubernetes--apps-helm-tasks-main.patch
    git_message: |
      Remove the install pyyaml

- name: Apply patch to remove the install pyyaml
  ansible.builtin.include_tasks: apply-patch.yml
