---

- name: Patch loadbalancer_apiserver to allow dynamic settings
  ansible.builtin.replace:
    path: "{{ kubespray_git_folder }}/inventory/sample/group_vars/all/all.yml"
    regexp: "^# loadbalancer_apiserver:.*$"
    replace: |-
      {% raw %}
      loadbalancer_apiserver:
        address: "{{ kubespray_loadbalancer_apiserver_address }}"
        port: "{{ kubespray_loadbalancer_apiserver_port }}"
      {% endraw %}

- name: Add patch to git
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - add
      - "{{ item }}"
  loop:
    - inventory/sample/group_vars/all/all.yml
  tags:
    - skip_ansible_lint

- name: Commit patch
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - commit
      - -m
      - |-
        allow loadbalancer_apiserver to be dynamically defined
  tags:
    - skip_ansible_lint
