- name: "Create branch"
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - branch 
      - new-features

- name: "Checkout branch"
  ansible.builtin.command:
    chdir: "{{ kubespray_git_folder }}"
    argv:
      - git
      - checkout
      - new-features
