- name: Patch local_path_provisioner_enabled
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/addons.yml"
      regexp : "^local_path_provisioner_enabled:[ |\t]+.*$"
      replace: "local_path_provisioner_enabled: {{ local_path_provisioner_enabled }}"
  when: local_path_provisioner_enabled is defined and local_path_provisioner_enabled

- name: Patch local_path_provisioner_claim_root
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/addons.yml"
      regexp : "^#[ |\t]+local_path_provisioner_claim_root:[ |\t]+.*$"
      replace: "local_path_provisioner_claim_root: {{ local_path_provisioner_claim_root }}"
  when: local_path_provisioner_enabled is defined and local_path_provisioner_enabled

- name: Patch apiserver_loadbalancer_domain_name
  replace:
    path   : "{{ dest_folder }}/group_vars/all/all.yml"
    regexp : "^## apiserver_loadbalancer_domain_name:.*$"
    replace: "apiserver_loadbalancer_domain_name: {% raw %}\"{{ kubespray_apiserver_loadbalancer_domain_name|default('') }}\"{%endraw%}"
  when:
  - apiserver_loadbalancer_domain_name is defined

#- name: Patch loadbalancer_apiserver
#  replace:
#    path   : "{{ dest_folder }}/group_vars/all/all.yml"
#    regexp : "^# loadbalancer_apiserver:.*$"
#    replace: "{{ loadbalancer_apiserver }}"
#  when:
#  - loadbalancer_apiserver is defined
#  - kube_lodabalancer_apiserver_enabled

- name: Patch upstream dns_servers
  replace:
      path   : "{{ dest_folder }}/group_vars/all/all.yml"
      regexp : "^# upstream_dns_servers:"
      replace: "{{ upstream_dns_servers }}"

- name: Patch http_server variable
  replace:
      path   : "{{ dest_folder }}/group_vars/all/all.yml"
      regexp : "^# http_proxy:.*$"
      replace: "http_proxy: \"{{ http_proxy }}\""

- name: Patch https_server variable
  replace:
      path   : "{{ dest_folder }}/group_vars/all/all.yml"
      regexp : "^# https_proxy:.*$"
      replace: "https_proxy: \"{{ http_proxy }}\""

- name: Patch crio registry
  replace:
      path   : "{{ dest_folder }}/group_vars/all/cri-o.yml"
      regexp : "^# crio_registry_auth:"
      replace: "{{ crio_registry_auth }}"

- name: Patch helm_enabled
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/addons.yml"
      regexp : "^helm_enabled:[ |\t]+.*$"
      replace: "helm_enabled: {{ helm_enabled }}"

- name: Patch metrics_server_enabled
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/addons.yml"
      regexp : "^metrics_server_enabled:[ |\t]+.*$"
      replace: "metrics_server_enabled: \"{{ metrics_server_enabled }}\""

- name: Patch local_volume_provisioner_enabled
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/addons.yml"
      regexp : "^local_volume_provisioner_enabled:[ |\t]+.*$"
      replace: "local_volume_provisioner_enabled: \"{{ local_volume_provisioner_enabled }}\""
  when: local_volume_provisioner_enabled is defined and local_volume_provisioner_enabled

- name: Patch kube_network_plugin
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_network_plugin:[ |\t]+.*$"
      replace: "kube_network_plugin: \"{{ kube_network_plugin }}\""

- name: Patch kube_version
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_version:[ |\t]+.*$"
      replace: "kube_version: \"{{ kube_version }}\""
  when: kube_version is defined 

- name: Patch kube_service_addresses
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_service_addresses:[ |\t]+.*$"
      replace: "kube_service_addresses: {{ kube_service_addresses }}"
  when: kube_service_addresses is defined

- name: Patch kube_pods_subnet
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_pods_subnet:[ |\t]+.*$"
      replace: "kube_pods_subnet: {{ kube_pods_subnet }}"
  when: kube_pods_subnet is defined

- name: Patch kube_network_node_prefix
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_network_node_prefix:[ |\t]+.*$"
      replace: "kube_network_node_prefix: {{ kube_network_node_prefix }}"
  when: kube_network_node_prefix is defined

- name: Patch kube_proxy_strict_arp
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^kube_proxy_strict_arp:[ |\t]+.*$"
      replace: "kube_proxy_strict_arp: {{ kube_proxy_strict_arp }}"

- name: Patch container_manager
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^container_manager:[ |\t]+.*$"
      replace: "container_manager: {{ container_manager }}"

- name: Patch enable_nodelocaldns
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^enable_nodelocaldns:[ |\t]+.*$"
      replace: "enable_nodelocaldns: {{ enable_nodelocaldns }}"

- name: Patch kube_oidc_auth
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_auth:.*$"
      replace: "kube_oidc_auth: {{ kube_oidc_auth }}"
  when:
  - kube_oidc_auth is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_url
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_url:.*$"
      replace: "kube_oidc_url: \"{{ kube_oidc_url }}\""
  when:
  - kube_oidc_url is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_client_id
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_client_id:.*$"
      replace: "kube_oidc_client_id: \"{{ kube_oidc_client_id }}\""
  when:
  - kube_oidc_client_id is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_username_claim
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_username_claim:.*$"
      replace: "kube_oidc_username_claim: {{ kube_oidc_username_claim }}"
  when:
  - kube_oidc_username_claim is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_username_prefix
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_username_prefix:.*$"
      replace: "kube_oidc_username_prefix: \"{{ kube_oidc_username_prefix }}\""
  when:
  - kube_oidc_username_prefix is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_groups_claim
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_groups_claim:.*$"
      replace: "kube_oidc_groups_claim: {{ kube_oidc_groups_claim }}"
  when:
  - kube_oidc_groups_claim is defined
  - kube_oidc_enabled

- name: Patch kube_oidc_groups_prefix
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^# kube_oidc_groups_prefix:.*$"
      replace: "kube_oidc_groups_prefix: \"{{ kube_oidc_groups_prefix }}\""
  when:
  - kube_oidc_groups_prefix is defined
  - kube_oidc_enabled

- name: Patch cluster_name (usually to remove the dot, as this is not accepted by cilium)
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^cluster_name:.*$"
      replace: "cluster_name: {{ cluster_name | default('cluster.local') }}"
  when:
  - cluster_name is defined and cluster_name|length > 0 

- name: Patch dns_domain to keep cluster.local local 
  replace:
      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-cluster.yml"
      regexp : "^dns_domain:.*$"
      replace: "dns_domain: {{ dns_domain | default('cluster.local') }}"
  when:
  - cluster_name is defined and cluster_name|length > 0 


#- name: Patch cilium
#  replace:
#      path   : "{{ dest_folder }}/group_vars/k8s_cluster/k8s-net-cilium.yml"
#      regexp : "^# see roles/network_plugin/cilium/defaults/main.yml.*$"
#      replace: "{{ cilium }}"
#  when: cilium is defined
- name: prepare cilium patch
  set_fact:
    # ABSOLUTE HORRIBLE SOLUTION to prevent rendering of cilium_etcd_endpoints:
    #    the raw prevents the inner line from rendering the first time, the "}}" solution prevents that is rendered second time
    cilium: |-
      cilium_version: "{{ cilium_version }}"
      # cilium_identity_allocation_mode: kvstore # kvstore or crd
      
      # Optional features
      cilium_enable_prometheus: true
      
      # Hubble
      ### Enable Hubble without install
      cilium_enable_hubble: true
      ### Enable Hubble Metrics
      cilium_enable_hubble_metrics: true
      ### if cilium_enable_hubble_metrics: true
      cilium_hubble_metrics:
       - dns
       - drop
       - tcp
       - flow
       - icmp
       - http
      
      ### Enable Hubble install
      cilium_hubble_install: true
      ### Enable auto generate certs if cilium_hubble_install: true
      cilium_hubble_tls_generate: true
      
      # FIXME hardcoded in roles/network_plugin/cilium/templates/cilium-config.yml.j2
      # bpf-ct-global-any-max      262144
      # bpf-ct-global-tcp-max      524288
      
      cilium_preallocate_bpf_maps: true
      
      ## https://github.com/cilium/cilium/issues/9117
      bpf-policy-map-max: "65536"
      cilium_clean_state: false
      cilium_clean_bpf_state: false
      cilium_config_extra_vars: {}
      cilium_hubble_enabled: true
      cilium_hubble_relay_enabled: true # default false
      cilium_hubble_ui_enabled: true # default false
      cilium_hubble_metrics_enabled: "{dns,drop,tcp,flow,port-distribution,icmp,http}"
      cilium_bpf_masquerade: true  # default false
      cilium_bpf_host_routing: false  # default true
      cilium_bpf_tproxy: true
      cilium_bpf_clock_probe: true # default false
      cilium_etcd_enabled: true # default false
      cilium_etcd_ssl: true # default false
      cilium_etcd_endpoints: "{% raw %}{{ "{{" }}{% endraw %} etcd_access_addresses.split(',') {% raw %}{{ "}}" }}{% endraw %}"
      cilium_labels: "k8s:k8s-app k8s:app k8s:name"
      cilium_local_redirect_policy: false
      cilium_prometheus_enabled:    true # default false
      cilium_ingresscontroller_enabled: true # default false
      #
      # Hubble values
      #
      cilium_hubble_ui_ingress_enabled: {{ cilium_hubble_ui_ingress_enabled }}
      cilium_hubble_ui_ingress_annotations:
      {% for key, value in cilium_hubble_ui_ingress_annotations.items() %}
        {{ key }}: "{{ value }}"
      {% endfor %}
      cilium_hubble_ui_ingress_hosts: {{ cilium_hubble_ui_ingress_hosts }}
      #
      # Mesh
      #
      cilium_clustermesh_useapiserver:  {{ cilium_clustermesh_useapiserver | default(false) }}
      cilium_cluster_name: {{ cilium_cluster_name }}
      cilium_cluster_id: {{ cilium_cluster_id }}

  when: cilium is not defined 

- name: Append Cilium config
  lineinfile:
    path: "{{ dest_folder }}/group_vars/k8s_cluster/k8s-net-cilium.yml"
    line: "{{ cilium }}"
      #when: cilium is defined

- name: Patch containerd - add registries
  replace:
      path   : "{{ dest_folder }}/group_vars/all/containerd.yml"
      regexp : "^# containerd_registries:.*$"
      replace: |-
        containerd_registries:
        {% for item in containerd_registries %}
          "{{ item }}": "{{ containerd_registries[item] }}"
        {% endfor %}
  when: containerd_registries is defined and containerd_registries|length > 0

- name: Patch containerd - add authentication
  replace:
      path   : "{{ dest_folder }}/group_vars/all/containerd.yml"
      regexp : "^# containerd_registry_auth:.*$"
      replace: |-
        containerd_registry_auth:
        {% for item in containerd_registry_auth %}
          - registry: {{ item.registry }}
            username: {{ item.username }}
            password: {{ item.password }}
        {% endfor %}
  when: containerd_registry_auth is defined and containerd_registry_auth|length > 0


